version: '3'
services:
  force-model:
    image: xdyn-force-grpc:python3
    command: harmonic_oscillator.py
    working_dir: /work
    volumes:
    - .:/work
    user: ${CURRENT_UID}
  xweave:
    image: sirehna/xweave
    working_dir: /work
    command: -f markdown -k python3 tutorial_10.pmd -o tutorial_10.md
    volumes:
    - .:/work
    user: ${CURRENT_UID}
    depends_on:
    - force-model
