before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
   stage: build
   script:
     - docker build -f Dockerfile -t xdyn .
     # - docker run --name cont_xdyn xdyn
     # - docker stop cont_xdyn
     # - docker rm cont_xdyn
