stages:
  - git_submodule
  - lint
  - cleanup_Docker
  - build

git_submodule:
   stage: git_submodule
   script:
     - git submodule sync --recursive
     - git submodule update --init --recursive

lint:
   stage: lint
   script:
     - cd code &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,eigen3-hdf5,gcovr,gtest,gmock,google-test,yaml-cpp} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..

cleanup_Docker:
   stage: cleanup_Docker
   script:
     - docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null || true
     - docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null || true

build:windows:
   stage: build
   script:
     - make fetch-ssc-windows
     - make cmake-windows
     - make package-windows
     - ./run_all_tests_windows.sh --gtest_filter=-HOS*:*erver*:*websocket*:ForceTests.bug_3210_no_interpolation_in_incidence_and_no_incidence_no_interpolation_in_period_no_transport:ForceTests.bug_3210_no_interpolation_in_incidence_no_interpolation_in_period_transport:ForceTests.bug_3210_no_interpolation_in_incidence_no_interpolation_in_period_transport_with_non_zero_t:ForceTests.bug_3210_no_interpolation_in_incidence_interpolation_in_period_transport_with_non_zero_t:BlockedDOFTest.should_not_throw_if_CSV_file_exists
     - mv build_windows/xdyn.zip .
   artifacts:
     when: on_success
     paths:
     - xdyn.zip
