stages:
  - git_submodule
  - lint
  - build
  - doc

git_submodule:
   stage: git_submodule
   script:
     - git submodule sync --recursive
     - git submodule update --init --recursive

lint:
   stage: lint
   script:
     - cd code &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,eigen3-hdf5,gcovr,gtest,gmock,google-test,yaml-cpp} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..

build:windows:
   stage: build
   before_script:
     - export GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN
   script:
     - make windows
     - mv build_win/xdyn.zip .
   artifacts:
     when: on_success
     paths:
     - xdyn.zip

build:debian:
   stage: build
   before_script:
     - export GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN
   script:
     - make debian
     - mv build_deb9_gcc820/xdyn.deb .
   artifacts:
     when: on_success
     paths:
     - xdyn.deb

doc:
   stage: doc
   script:
     - make doc_pweave
   dependencies:
     - build:debian
   artifacts:
     when: on_success
     paths:
     - doc.html
