stages:
  - lint
  - build
  - test
  - doc

default:
  before_script:
    - make submodule

lint:
   stage: lint
   script:
     - make lint

build:windows:
   stage: build
   script:
     - make windows
     - mv build_win_posix/xdyn.zip .
   artifacts:
     when: on_success
     paths:
     - xdyn.zip

build:debian:
   stage: build
   script:
     - make debian
     - mv build_deb10/xdyn.deb .
   artifacts:
     when: on_success
     paths:
     - xdyn.deb

test:grpc:
    stage: test
    script:
     - docker build . --tag xdyn
     - make docker_grpc_force_model
     - make docker_grpc_waves_model
     - cd grpc_tests && make

doc:
   stage: doc
   script:
     - mkdir -p build_deb10 && cp xdyn.deb build_deb10/.
     - make doc -W build-debian
   dependencies:
     - build:debian
   artifacts:
     when: on_success
     paths:
     - doc.html
