stages:
  - lint
  - build
  - doc

lint:
   stage: lint
   script:
     - cd code &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,eigen3-hdf5,gcovr,gtest,gmock,google-test,yaml-cpp} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..

build:windows:
   stage: build
   script:
     - make windows
     - mv build_win_posix/xdyn.zip .
   artifacts:
     when: on_success
     paths:
     - xdyn.zip

build:debian:
   stage: build
   script:
     - make debian
     - mv build_deb9/xdyn.deb .
   artifacts:
     when: on_success
     paths:
     - xdyn.deb

doc:
   stage: doc
   script:
     - mkdir -p build_deb9 && cp xdyn.deb build_deb9/.
     - make doc -W build-debian
   dependencies:
     - build:debian
   artifacts:
     when: on_success
     paths:
     - doc.html
