stages:
  - git_submodule
  - lint
  - build

git_submodule:
   stage: git_submodule
   script:
     - git submodule sync --recursive
     - git submodule update --init --recursive

lint:
   stage: lint
   script:
     - cd code &&
       if grep --recursive --include={*.cpp,*.c,*.hpp,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt}
               --exclude-dir={eigen,eigen3-hdf5,gcovr,gtest,gmock,google-test,yaml-cpp} -P "\t" . ;
       then echo "Tabs found in the lines shown above."; false;
       else echo "Repo passed no-tabs check."; fi &&
       cd ..

build:windows:
   stage: build
   before_script:
     - export GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN
   script:
     - make windows
     - ./run_all_tests_windows.sh --gtest_filter=-HOS*:*erver*:*websocket*:BlockedDOFTest.should_not_throw_if_CSV_file_exists
     - mv build_windows/xdyn.zip .
   artifacts:
     when: on_success
     paths:
     - xdyn.zip

build:debian:
   stage: build
   before_script:
     - export GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN
   script:
     - make debian
     - ./run_all_tests_debian.sh --gtest_filter=-HOS*
     - mv build_debian/xdyn.deb .
   artifacts:
     when: on_success
     paths:
     - xdyn.deb

build:doc:
   stage: build
   script:
     - make doc
   artifacts:
     when: on_success
     paths:
     - doc.html

build:doc_pweave:
   stage: build
   script:
     - cd doc_user
     - docker build . --tag pweave
     - docker run -it pweave:latest /bin/sh -c "pwd && ls"
     - cd ..
