version: '3'
services:
  server:
    build: ../code/waves_grpc/python_server
    user: ${CURRENT_UID}
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint: ./wait-for-it.sh server:50051 -s -t 20 -- xdyn grpc.yml --dt 0.1 --tend 0.2 -o tsv
    volumes:
    - .:/data
    user: ${CURRENT_UID}
    depends_on:
    - server
