version: '3'
services:
  force-model:
    build: .
    entrypoint: ["/bin/bash", "/entrypoint.sh", "/work/harmonic_oscillator.py"]
    working_dir: /work
    volumes:
    - .:/work
    - ../../code/grpc:/proto
    - ../../code/waves_grpc:/proto_waves
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint:  ./wait-for-it.sh force-model:9002 -s -t 20 -- xdyn tutorial_10_gRPC_force_model.yml --dt 0.1 --tend 1 -o tsv
    volumes:
    - .:/data
    depends_on:
    - force-model
