version: '3'
services:
  force-model:
    image: xdyn-force-grpc:python3
    command: model.py
    working_dir: /work
    volumes:
    - .:/work
    user: ${CURRENT_UID}
  xdyn:
    image: xdyn
    working_dir: /data
    entrypoint: |
           ./wait-for-it.sh force-model:9002 -s -t 20 --
            xdyn xdyn.yml --dt 0.1 --tend 0.5 -o tsv
    volumes:
    - .:/data
    user: ${CURRENT_UID}
    depends_on:
    - force-model
